### ISSUE TITLE
Trapping focus when using keyboard

### ISSUE THREAD

**Issue by umpirsky** [Tudmotu/gnome-shell-extension-clipboard-indicator#103]
When navigating without a mouse, only with keyboard, it traps focus.

Reproduce with:

1. `Super + M`
1. `Right arrow` x 5
1. It gets stuck on clipboard indicator

It should continue to next widget instead.

**Comment by umpirsky** [comment]
Thanks, nice one. But still, this deserves a fix.

**Comment by Tudmotu** [comment]
Hi @umpirsky !
Thank you for reporting this, and thanks @smichel17 for the workaround.
I agree this requires a fix. I think the focus is good for quickly filtering clips when opening the menu with the shortcut, but shouldn't happen otherwise. If any of you would like to take a shot at it, I would greatly appreciate it :smiley:

**Comment by smichel17** [comment]
Agreed, although I feel like it should maybe be reported as a bug in gnome, too; empty text boxes should not capture left & right arrow keystrokes.
