### ISSUE TITLE
Move favorites to bottom  

### ISSUE THREAD

**Issue by rahidelvi** [Tudmotu/gnome-shell-extension-clipboard-indicator#116]
If you're using the keyboard to review your recent clips you'll have to hit the down arrow a couple of times to get past your favs. The search helps, but that's more keystrokes.

Would it be possible to have an option to position the favorites at the bottom of the clip list?

Thank you for sharing this extension.

**Comment by Tudmotu** [comment]
Thank you for this idea! I like it :)
Unfortunately I have little time to implement new features at the moment. If you would like to contribute this feature, I would greatly appreciate it. This should not be too difficult to implement - add an option in the settings, then add the [favorites section](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L146) at the bottom instead of the top.
And if you need directions I can help with that :)

**Comment by b00f** [comment]
> Would it be possible to have an option to position the favorites at the bottom of the clip list?

Moving favorites to the bottom of the list has another effect. You might refer to favorites more often. So in case you want to reach them you will hit many more down keys. 

I think this option is not something useful.
