### ISSUE TITLE
Security of passwords cached in the extension.

### ISSUE THREAD

**Issue by NinjaTurtle007** [Tudmotu/gnome-shell-extension-clipboard-indicator#130]
I read there are couple discussion about protecting it from caching passwords (copied from KeePassX) for example, but nothing implemented yet right?

So, at the current state where is the clipboard history data saved? What happens with it on shutdown?
Which other applicatons can access it?

This is great extension but just feels that can be used as a side channel to compromise one's security.

**Comment by Tudmotu** [comment]
Hi @NinjaTurtle007,
Thanks for letting me know this is important to you.
At the moment, I do not plan on implementing anything as I have very little time and it is unclear if a solution is even possible.
If you are able to investigate this issue and try to see if you can implement it, I would greatly appreciate it. :slightly_smiling_face: 

As for your questions:
1. The data is saved in ``~/.cache/clipboard-indicator@tudmotu.com/registry.txt``
1. It is persisted through shutdowns unless you turn on the "Cache only favorites" setting
1. Any other application or user can read this file

Closing this since questions were answered. The KeePass discussion can continue in #46.
