### ISSUE TITLE
Feature/Security request: add option for making clipboard history saved in volatile non-persistent memory

### ISSUE THREAD

**Issue by mirko** [Tudmotu/gnome-shell-extension-clipboard-indicator#138]
I'm happily using the clipboard-indicator, however today, after I rebooted my machine, I noticed, that the history is still there.

Apparently the clipboard history is stored across reboots, which is not what I expected.

As a matter of fact, I would have expected it being stored in volatile non-persistent memory, as the clipboard very well contains sensitive information which I didn't expect being written on persistent storage.

I herewith kindly ask for an option to make this behaviour configurable and - if this is happening - encourage to have the clipboard being saved on persistent storage a non-default opt-in.

Unfortunately, as much as I find this extension convenient, as much this is a no-go behaviour - at least for me.

Nevertheless, thanks again for the effort - and thanks in advance for reading this feature request and potentially even taking it seriously :)

**Comment by Tudmotu** [comment]
In the settings screen, you can set the "cache only favorites" option, which should do what you are looking for. It still caches the favorites, but the other items will be removed on reboot/logout.

**Comment by mirko** [comment]
Thanks, I looked at the settings screen, however obviously didn't realise the meaning of "caching".
Can we still change its default value though?

**Comment by Tudmotu** [comment]
We will not change the default value. :\\
This extension has been working like this for long and I personally prefer it to persist.
I think we can change the text for that option in the settings to make it clearer.

**Comment by Tudmotu** [comment]
I'm closing this thread because I feel it has been answered. :slightly_smiling_face:

**Comment by mirko** [comment]
Sure, fair enough and thanks! :)

**Comment by attila-lendvai** [comment]
@Tudmotu here i am, 3 years later.

i was utterly surprised that this extension is persisting my passwords in clear text, somewhere on the disk i couldn't even find... and then i looked at the source code to decypher what's happening, when i finally ended up here to realize what that mysterious "cache only favorites" option does. it's completely un-intuitive. i was looking for this feature, and i still couldn't find it.

this is a mayor security issue, therefore i suggest the following:

1. rename the option to something like "Persistent history", or "Save history"
2. make it default to **not** saving the history to the disk, unencrypted

**Comment by attila-lendvai** [comment]
a few more years passed, and the situation is still the same: passwords in the clipboard history are saved in clear text by default, and the option to turn it off is called "Cache only pinned items".

cache =/= save as clear text on the disk.

i.e. persist it for anyone to access it on a non-encrypted install with a bootable pendrive, or for any trojan that happened to be installed on the machine...

i hardly can think of this as anything else than an intentional compromise.

**Comment by Tudmotu** [comment]
@attila-lendvai You are welcome to fork this extension and implement the behavior you want. If you need any help with that I will help you.
All the clipboard indicators you see on e.g.o are forks of my extension. You are welcome to fork it as well, that's why it's MIT, so people can fork without any worries :slightly_smiling_face: 

The options you have are:
1. Fork and do whatever you want
2. Open a PR on GNOME to add some API that identifies passwords so this extension can avoid saving them (that would be really cool)
3. Use the shortcuts to come in & out of "Private Mode" quickly
4. Use the "remove history on boot" option in the settings:
![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/506487/2fa5e714-b9ad-4af6-8ea6-029cb5f442d9)

**Comment by methuselah-0** [comment]
"remove history on boot" vs "reboot" sounds like 2 different things: are you clearing the cached passwords when the program quits for an issued reboot or when the program starts when the system is booted?

**Comment by Tudmotu** [comment]
@methuselah-0 Yeah actually neither is technically correct. I believe it deletes the cache when the extension is "enabled" so I think it deletes it when you log in (even if you don't reboot). It was a PR so I'm not 100% sure of the details.

**Comment by methuselah-0** [comment]
@Tudmotu okay thanks for explaining. I do want to second the sentiment of @attila-lendvai that saving something as sensitive as clipboard is unexpected behaviour and cache is usually considered temporary (unless referred to as "persistent cache") so the behaviour of saving clipboard history to disk would be good to change so it's not by default. Maybe changing the default location of this to /tmp/xxx.cache would be an easy fix? I'm not versed enough in the codebase to do it myself but I don't like the idea of having my passwords unknowingly copied to clear text on disk.

**Comment by Tudmotu** [comment]
As I've said before, I will not change the default behavior.

The "Cache only pinned items" option in the settings should accomplish exactly what you are after. It keeps the entire history in memory instead of on disk.

As to changing the path of the registry ― I am open to accepting a PR that introduces an option in the settings to change the path of the registry data.

Regarding terminology ― I agree terminology is bad. "Cache" is not the correct word. I will accept a PR that modifies these texts in the settings:
- "Max cache file size (MB)" --> "Max history file size (MB)"
- "Cache only pinned items" --> "Persist only pinned items"

**Comment by Tudmotu** [comment]
I beg you to create a better fork and take all these users. Please. It would be a huge load off of me. Honestly I barely have time to maintain this extension, but I do what I can because I know many users are counting on it. When something goes wrong I get literally dozens of emails instantly. It would be great if someone manages to create a more popular extension. Many have tried and failed. I am currently excited to see where [Pano](https://extensions.gnome.org/extension/5278/pano/) goes. Looks very promising. But alas it is not yet popular enough, probably due to the external dependencies requirement which I purposefully tried to avoid with this extension.

I also used to have some hope someone from the contributors (of which there are many) would someday take the reigns but by now most of the contributors who actually know the code have moved on, while new contributors find it difficult grappling with the ancient codebase. This extension has been live since 3.10 (lmao, remember when GNOME used to be versioned 3.x 😂) and so the codebase had to go through all the API changes of GNOME which left it in terrible state.

Anyway Atilla thank you for listening and using the extension, I'm glad you find it useful and hope one day you'll find an even better clipboard manager 🙏🏼

**Comment by attila-lendvai** [comment]
@Tudmotu i'm not using sw whose author reacts to security concerns the way you do.

ever since i realized what's explained above, i'm a happy user of [gpaste](https://github.com/Keruspe/GPaste).

the reason i'm here is just that i care about clueless people being misled...

**Comment by Tudmotu** [comment]
Awesome, gpaste is definitely a great choice! :slightly_smiling_face:

**Comment by mirko** [comment]
Original author of this ticket here. As I still stand with really not being happy about the design decision in question, this is a FOSS project lot's of people appear to be happy using. While - potentially especially because of the range of influence - I also think users should not be fooled into false security, I truly don't believe the author of this software means anyone any harm.
Given that, long story short: @attila-lendvai, while we agree on the objective: given your wording and tone, I'm sorry I gotta say that you're out of line and @Tudmotu definitely does not deserve being treated like that.

**Comment by Tudmotu** [comment]
Thank you @mirko 🙏🏼

**Comment by attila-lendvai** [comment]
@mirko i hear you. i'm also a long time opensource developer, i understand your perspective very well, and i even agree with it.

but! rename the project to *Tudmotu's clipboard indicator*, and/or spend 5 minutes to address this issue (without much of any downside), and i wouldn't have used my stronger wording. short of doing that, i'm upset about this longstanding situation, and i'm expressing it in my words to be an advocate for all those users that i encounter who are freaking out when realizing this. it could have been addressed trivially years ago, without much of any downside besides a couple of minutes of work. i have even opened a (rejected) PR to simplify this to the point of a click. that click did not happen, and the argument was that "i like it this way".

recently gpaste build broke in guix for a while, and users of gpaste switched to this extension. in the discussion i saw once again the same frightened contemplation of the attack vector that was open for them who knows how long...

freedom and responsibility are two sides of the same coin: you have the freedom to create and publish any opensource software, but it inevitably comes with the responsibility towards your fellow men and your creation. "i like it this way" is not a valid response to a security concern, and does not reflect much responsibility in my eyes. hence my harsher wording.

> @Tudmotu definitely does not deserve being treated like that.

and what treatment do the clueless users deserve?

**Comment by Tudmotu** [comment]
Attila, you are aware that GPaste also saves your [history to a file](https://github.com/Keruspe/GPaste/blob/6da7b5cde09ee17746a3e5235feab9a1066f50fe/src/daemon/tmp/gpaste-storage-backend.c#L19), yes?

**Comment by attila-lendvai** [comment]
> Attila, you are aware that GPaste also saves your [history to a file](https://github.com/Keruspe/GPaste/blob/6da7b5cde09ee17746a3e5235feab9a1066f50fe/src/daemon/tmp/gpaste-storage-backend.c#L19), yes?

only when enabled, and the setting is called "Save history", not "Cache only favorites"... the primary source of my upset is that i **did** look for this setting to disable it after install, and i still have missed it.

but you do have a point in that i should also open an [issue in gpaste](https://github.com/Keruspe/GPaste/issues/442) for having that disabled by default.

**Comment by methuselah-0** [comment]
> As I've said before, I will not change the default behavior.
> 
> The "Cache only pinned items" option in the settings should accomplish exactly what you are after. It keeps the entire history in memory instead of on disk.
> 
> As to changing the path of the registry ― I am open to accepting a PR that introduces an option in the settings to change the path of the registry data.
> 
> Regarding terminology ― I agree terminology is bad. "Cache" is not the correct word. I will accept a PR that modifies these texts in the settings:
> 
> * "Max cache file size (MB)" --> "Max history file size (MB)"
> * "Cache only pinned items" --> "Persist only pinned items"
> 
> Alternatively, I would also accept a PR that removes the "Cache only pinned" option and instead introduces a dropdown in the settings, labeled "Persist to disk" with the options "Both" (default), "Only Pinned".

I like your suggestions as an improvement, but it still lacks addressing what I think is very important - user awareness of the default. Would you accept a PR that would introduce displaying a red warning triangle for when a setting is active that saves history to disk (so by default a warning would be displayed), together with a checkbox option to "Disable warning when history can be saved to disk"? That would warn all existing users at next upgrade, without changing the behaviour, and allow them to disable the warning if they find it annoying? I'm not saying I would implement this myself, but making it clear that you would accept such a PR (or a similar one if you like the idea), might improve chances that someone will do the work.

**Comment by Tudmotu** [comment]
I don't think a warning is necessary.
I will say, in case it's not clear ― 99% of users **expect** their clipboard to be saved between reboots. This *is* the standard behavior. Nothing here is unexpected.

As I said, I would accept a PR that lets users set their clipboard data directory. That would be very nice actually.

**Comment by attila-lendvai** [comment]
> 99% of users **expect** their clipboard to be saved between reboots

99% of the users don't care about security... but does that make it ethical to hack them? or expose them on an attack surface that they don't understand just by installing a clipboard **indicator**?
