### ISSUE TITLE
Setting HISTORY_SIZE problem

### ISSUE THREAD

**Issue by jusa213** [Tudmotu/gnome-shell-extension-clipboard-indicator#21]
Hello

Thanks for this useful extensions.
I tried to set the history size to 500 so I changed the values in prefs.js

> this.field_size = new Gtk.SpinButton({
>             adjustment: new Gtk.Adjustment({
>                 lower: 1,
>                 upper: 500,
>                 step_increment: 1

and in extensions.js to

> let MAX_ENTRY_LENGTH     = 500

So with GNOME Tweak Tool I can set the history size up to 500 but if I close the settings screen and reopen it, the history size is back to 50. How to change history size the right way?

Thx for helping out here.

**Comment by Tudmotu** [comment]
Hi :)
I believe you need to edit the schema file (the ``.gschema.xml`` file in ``schemas/`` directory), then recompile the schema file using ``glib-compile-schemas``, and reload the shell.

*But* I highly recommend that you don't change it to more than 50, because this extension is not built to endure a large cache. It will probably slow down your entire shell. :\
