### ISSUE TITLE
Primary selection

### ISSUE THREAD

**Issue by thisboyiscrazy** [Tudmotu/gnome-shell-extension-clipboard-indicator#34]
Can this sync / add from primary selection?

**Comment by jhaar** [comment]
ditto. I've just moved to Fedora-24beta and discovered this extension - great! However, it's confusing how the old-fashion X11 primary selection isn't "synced"? In particular relying on double-clicking on words in terminals to paste into other terminals is something I do all the time - but only for the current selection of course. I'd like them to be remembered so I can use them several selections later. I mention terminals because you can't Ctrl-C selections to force them into your clipboard extension - like you can do with other more GUI apps

**Comment by Tudmotu** [comment]
Hi guys,
This is an old feature request, but I didn't find the time to implement it. Please checkout #8, it also contains a mock for how such a thing will look like and I would love your opinion.

Thanks

**Comment by thisboyiscrazy** [comment]
I like, but i just want to make sure middle click and Crtl+V paste the same thing.

**Comment by Tudmotu** [comment]
Closing in favor of #8
