### ISSUE TITLE
Favorites Gone / Removed

### ISSUE THREAD

**Issue by hopeinformer** [Tudmotu/gnome-shell-extension-clipboard-indicator#360]
After restarting my computer all of my favorite clipboard items are suddenly gone and Private Mode is activated. Where did private mode come from? How do I get my favorites back?

**Comment by Tudmotu** [comment]
Unfortunately if you activated private mode by accident, your items are gone :frowning_face: 
Deactivate private mode so your clipboard will not clean itself on restart.
I am closing this since this is 28 days old and I assume you've figured it out :)

Feel free to comment if you still have an issue.
