### ISSUE TITLE
Do not save content copied from a specific app

### ISSUE THREAD

**Issue by xplosionmind** [Tudmotu/gnome-shell-extension-clipboard-indicator#380]
Allow users to select a set of apps for which this extension is disabled. For example, I could choose that anything I copy from [KeepassXC](https://keepassxc.org) is not stored, so that I do not risk any of my passwords to be exposed.

**Comment by Tudmotu** [comment]
This has been discussed multiple times in the past, but unfortunately no one has ever come up with a way of actually achieving this in a GNOME extension :disappointed: 

I am closing this issue since it's been discussed previously, but if you have any idea how to implement this feature, please reopen.
