### ISSUE TITLE
Settings dialogue can be opened infinitely many times

### ISSUE THREAD

**Issue by ctorgalson** [Tudmotu/gnome-shell-extension-clipboard-indicator#431]
Clicking the "Settings" link in the Clipboard Indicator menu will open a new copy of the Settings window regardless of whether any instances of the window are already open. The same thing happens when clicking the gear icon in the Extensions app.

I discovered this because the window isn't focused by clicking the "Settings" link (i.e. if the window is behind any other window, it stays behind it rather than gaining focus and coming to the foreground).

Ubuntu 20.04, extension installed via extensions.gnome.org browser plugin.

![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/1063424/abf5e5f5-6f2a-4c92-ad57-ffdc79973bac)

**Comment by Tudmotu** [comment]
It seems you are using an old version of the extension. Since GNOME 45, all previous versions are not supported anymore due to backwards incompatibility issues.

This does not seem to happen with the latest version of the extensions on GNOME 45.

I am closing this issue, but I appreciate you taking the time to report this :pray:

**Comment by ctorgalson** [comment]
That's good to know. I was looking for clipboard tools for Ubuntu 22.04 or 24.04, so I'll put this one back on the list :)
