### ISSUE TITLE
Arrow key navigation randomly stops working

### ISSUE THREAD

**Issue by valorin** [Tudmotu/gnome-shell-extension-clipboard-indicator#84]
Found a strange issue:

Using the arrow keys (i.e. `up` / `down`) to navigate the history list randomly stops working. Once it stops working, you need to manually move the mouse to the menu to select an item from the history list.

I haven't figured out how to trigger it to fail yet... :-(

Let me know if there is any debugging I can do to help track it down.

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
> gnome-shell --version
GNOME Shell 3.26.1
```

**Comment by ewh** [comment]
I am also running the same software configuration (ubuntu: 17.10, gnome: 3.26.1). I am _never_ able to use arrow keys to navigate `up`/`down` without first hovering over the list of entries. My situation seems worse than the original poster (but very similar) since his situation only seems to fail randomly. Once I hover over the entries one of the entries will be highlighted so that arrow keys work again. It seems to be an issue with focus. When running earlier versions of ubuntu/gnome, the `up`/`down` arrow keys would work immediately (without requiring any input from the mouse).

Since I am also able to reproduce this behavior, I am also available for any debugging which might be useful. (I am not at all familiar with the architecture of writing gnome extensions, but let me know if I might help with troubleshooting.)

**Comment by ewh** [comment]
After further experimentation, it seems this _might_ be a larger issue than just Clipboard Indicator. Navigating the Clipboard Indicator using arrow keys is part of general navigation of the Gnome top menu bar with arrow keys. All of the top bar menus also will not work for me with arrow keys unless the mouse hovers over the menu entries first. Could this be a more general issue with Gnome or the window manager?

(I would be curious to see if @valorin experiences anything similar.)

**Comment by valorin** [comment]
Yep, you're right @ewh - it does affect the whole top menu bar. I hadn't noticed before.

I also haven't been able to get it working again - my "randomly stops working" has turned into: "it doesn't work anymore".

**Comment by Tudmotu** [comment]
Hi,
Thank you both for reporting this.
I am on Arch with 3.26, and arrow navigation works for me. :\

This might be some focus issue, and could be solved by focusing the first entry whenever the menu opens.

**Comment by ewh** [comment]
@valorin @Tudmotu I have another data point. All of my machines where keyboard arrow navigation worked in Ubuntu 17.04 are broken in 17.10. 17.10, by default logs in using Wayland (I think 17.04 defaulted to XOrg). If I select to log in using XOrg in 17.10, the arrow keys work again.

If @valorin could also confirm this, that would certainly be another interesting data point.

All of this information might suggest that there is some compatibility issue with 17.10 running in XOrg vs. Wayland and that Clipboard Indicator is not really a factor.
