### ISSUE TITLE
[Feature request] Pin value

### ISSUE THREAD

**Issue by erzzo** [Tudmotu/gnome-shell-extension-clipboard-indicator#85]
Hi,
I used clipIt (https://apps.ubuntu.com/cat/applications/precise/clipit/) on Unity, but after I switched to gnome I found this extension.
Only one feature, that I need here, is to store a persistent value into the history list. I have a special character in my name and it's super useful for everyday usage. And I think it would be great for other people too (not only for that name thing).

How it looks like: 
![screenshot from 2017-10-23 14-29-46](https://user-images.githubusercontent.com/886192/31889048-add699d8-b7fe-11e7-946e-87804035df7c.png)

ö is the static item

**Comment by Tudmotu** [comment]
Hi @erzzo 
This is a very good suggestion (which was also raised in #37), and something that I would like to do some when, but unfortunately I don't have the time to implement this at the moment.
If you would like to implement this, I would greatly appreciate it and will help you with it as much as i can :smiley:

**Comment by danboid** [comment]
I have just come here to request the exact same feature - it seems errzo beat me by 9 hours!

I'm a heavy user of parcellite under X desktops, especially it 'persistent history' feature which is essentially what errzo is requesting here. Its the killer feature of clipboard tools for me.

I don't know any js but I know python and shell so I'll work it out easily enough. I'll have a go at adding this soon if no-one beats me to it.

**Comment by erzzo** [comment]
The stage is your's @danboid :+1:

**Comment by danboid** [comment]
I've had a quick look at this. I am new to both JS and Clutter/GNOME dev. Understanding JS won't be a problem, it is learning Clutter that represents the real effort in getting started here. My only experience with GUI programming so far has been PyQt but that seems to be much better documented than Clutter's JS bindings - in fact right now I'm under the impression that there isn't any official documentation for using Clutter via JS? The nearest I've found to some clutter/JS docs is this:

http://mathematicalcoffee.blogspot.co.uk/2012/09/gnome-shell-javascript-source.html

That's from 2012 though so in FOSS terms its archaic. Is there not some more recent docs?

I envision this feature to work as follows. The clipboard menu will have two areas: the 'normal' items in the upper area and the pinned/persistent items in the lower area. The items in the upper/normal section can be activated, removed or moved into the persistent list, whereas the pinned items can only be activated or removed.

My main question right now (apart from the docs issue) is how does @Tudmotu recommend I try implementing moving items into the persistent list? My preferred choice would be the user could right-click on an entry then choose 'Move to persistent' (or however we choose to phrase it - I don't think 'pin' is a good choice as it is getting moved) but I don't think that is an option because the popupmenu items don't seem to support being right-clicked so I think that leaves us with either adding a new icon to the right side of every upper menu item (next to the remove icon) or doing it via drag n' drop. The drag and drop method would mean less UI clutter but might not be as obvious and maybe isn't even possible within the GNOME popup menu?

**Comment by Tudmotu** [comment]
Some when, a long time ago (couple of years), someone made a fork of this extension with this exact functionality - a drag-n-drop favorites section. At the time, I tried to merge it, but it was too diverged for me to be able to do that. I don't remember who that was or where their repository is unfortunately...

Anyway, drag-n-drop is possible, but I personally would prefer a start/bookmark icon next to the X button (but at a safe distance from it).

The implementation would require some changes to the cache file structure, to contain two lists: favorites and regular history. When the "favorite" button is clicked on an item, it will be moved from the regular to the favorites and back.
We need to add another menu section that will display the favorite clips, and we need to make sure the keyboard shortcuts support navigating between favorites/regular list (when you reach the end of the favorites, it moves to the regular list, when it reaches the end of the regular list it moves back to the favorites)

@danboid - you can find the clutter reference here: https://developer.gnome.org/clutter/stable/
It is for C, but the JS bindings are basically the same.
You can also find the GJS reference here: http://devdocs.baznga.org/
But generally speaking, there is not a lot of documentation.

**Comment by freeroot** [comment]
Hello,

To implement favorites in PR #92, I add a boolean to each items which is toggle by a ⭐️ icon. Favorites are never automatically deleted except by clicking on the X icon next to it.

Those items are not moved to another menu as @Tudmotu suggest to let the list in order of history. I would like to know if you think it's enough or create another menu is required for a good enhancement.

**Comment by freeroot** [comment]
Hello,

To implement favorites in PR #92, I add a boolean to each items which is toggle by a ⭐️ icon. Favorites are never automatically deleted except by clicking on the X icon next to it.

Those items are not moved to another menu as @Tudmotu suggest to let the list in order of history. I would like to know if you think it's enough or create another menu is required for a good enhancement.

**Comment by danboid** [comment]
I'm glad I didn't get started on this seeing as freeroot seems to have done it already. It looks like his modifications do what I want although I haven't been able to get his PR code to work under GNOME 3.26.1 - GNOME Shell fails to load.

The only small advantage I can think of for having a separate list for favourites is that it makes it a little quicker to select them via the keyboard / directional arrows if they're all grouped together at the top or bottom but it could also be argued having just one fave list is cleaner.

**Comment by Tudmotu** [comment]
I think we start with favorites without a separate menu, and see in the future if we want to put the effort into a different section.

**Comment by freeroot** [comment]
@danboid I forget to compile schemas again. It done so now it works again.

**Comment by danboid** [comment]
freeroot is right in saying the faves list would be best placed under the search box ie at the top of the menu/list.

I would be happy if the search only searched the non-fave items - in fact I think thats the best way for it to work. Personally, I'm unlikely to have so many faves that I need to search through them.

I've hit a couple of probs with the current code but I'll discuss them in the comments for the PR.
